# Generated by Django 2.2 on 2023-06-10 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recycle', '0066_auto_20230302_2307'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_image_big',
            field=models.ImageField(default='placeholder.jpg', upload_to='', verbose_name='Большое изображение продукта'),
        ),
        migrations.AlterField(
            model_name='article',
            name='article_slug',
            field=models.CharField(default='article2023-06-10 14:33:46.738816', max_length=200, verbose_name='URL'),
        ),
        migrations.AlterField(
            model_name='category',
            name='cat_slug',
            field=models.CharField(default='slug2023-06-10 14:33:46.661164', max_length=200, verbose_name='URL'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_slug',
            field=models.CharField(default='product2023-06-10 14:33:46.737949', max_length=200, verbose_name='URL'),
        ),
        migrations.AlterField(
            model_name='region',
            name='region_slug',
            field=models.CharField(default='region2023-06-10 14:33:46.739505', max_length=200, verbose_name='URL'),
        ),
    ]
