# Generated by Django 3.2.4 on 2024-02-21 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recycle', '0069_auto_20240221_1214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='article_slug',
            field=models.CharField(default='article2024-02-21 12:44:24.652694', max_length=200, verbose_name='URL'),
        ),
        migrations.AlterField(
            model_name='category',
            name='cat_slug',
            field=models.CharField(default='slug2024-02-21 12:44:24.625381', max_length=200, verbose_name='URL'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_slug',
            field=models.CharField(default='product2024-02-21 12:44:24.652127', max_length=200, verbose_name='URL'),
        ),
        migrations.AlterField(
            model_name='region',
            name='region_slug',
            field=models.CharField(default='region2024-02-21 12:44:24.653164', max_length=200, verbose_name='URL'),
        ),
        migrations.AlterField(
            model_name='tweet',
            name='tweet_slug',
            field=models.CharField(default='article2024-02-21 12:44:24.654685', max_length=200, verbose_name='URL'),
        ),
        migrations.AlterField(
            model_name='tweet',
            name='tweet_type',
            field=models.CharField(blank=True, choices=[('Новость', 'Новость'), ('Выезд', 'Выезд'), ('Внимание', 'Внимание')], max_length=10, verbose_name='Тип заметки'),
        ),
    ]
