# Generated by Django 3.2.4 on 2024-02-22 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recycle', '0071_auto_20240222_1342'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweet',
            name='region',
            field=models.ManyToManyField(blank=True, to='recycle.Region'),
        ),
        migrations.AlterField(
            model_name='article',
            name='article_slug',
            field=models.CharField(default='article2024-02-22 13:43:35.982716', max_length=200, verbose_name='URL'),
        ),
        migrations.AlterField(
            model_name='category',
            name='cat_slug',
            field=models.CharField(default='slug2024-02-22 13:43:35.956106', max_length=200, verbose_name='URL'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_slug',
            field=models.CharField(default='product2024-02-22 13:43:35.982226', max_length=200, verbose_name='URL'),
        ),
        migrations.AlterField(
            model_name='region',
            name='region_slug',
            field=models.CharField(default='region2024-02-22 13:43:35.983128', max_length=200, verbose_name='URL'),
        ),
        migrations.AlterField(
            model_name='tweet',
            name='tweet_slug',
            field=models.CharField(default='article2024-02-22 13:43:35.984448', max_length=200, verbose_name='URL'),
        ),
    ]
