# Generated by Django 2.2 on 2023-03-02 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recycle', '0065_auto_20220905_1949'),
    ]

    operations = [
        migrations.AddField(
            model_name='punkt',
            name='punkt_negative',
            field=models.IntegerField(blank=True, default=0, verbose_name='Негативный рейтинг'),
        ),
        migrations.AddField(
            model_name='punkt',
            name='punkt_positive',
            field=models.IntegerField(blank=True, default=0, verbose_name='Позитивный рейтинг'),
        ),
        migrations.AlterField(
            model_name='article',
            name='article_slug',
            field=models.CharField(default='article2023-03-02 23:07:26.978390', max_length=200, verbose_name='URL'),
        ),
        migrations.AlterField(
            model_name='category',
            name='cat_slug',
            field=models.CharField(default='slug2023-03-02 23:07:26.949271', max_length=200, verbose_name='URL'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_slug',
            field=models.CharField(default='product2023-03-02 23:07:26.977630', max_length=200, verbose_name='URL'),
        ),
        migrations.AlterField(
            model_name='region',
            name='region_slug',
            field=models.CharField(default='region2023-03-02 23:07:26.979038', max_length=200, verbose_name='URL'),
        ),
    ]
