# Generated by Django 5.1.1 on 2024-10-22 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recycle', '0075_clientsales_alter_article_article_slug_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='sales',
        ),
        migrations.AlterField(
            model_name='article',
            name='article_slug',
            field=models.CharField(default='article2024-10-22 14:48:09.922202', max_length=200, verbose_name='URL'),
        ),
        migrations.AlterField(
            model_name='category',
            name='cat_slug',
            field=models.CharField(default='slug2024-10-22 14:48:09.920701', max_length=200, verbose_name='URL'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_slug',
            field=models.CharField(default='product2024-10-22 14:48:09.920701', max_length=200, verbose_name='URL'),
        ),
        migrations.AlterField(
            model_name='region',
            name='region_slug',
            field=models.CharField(default='region2024-10-22 14:48:09.922706', max_length=200, verbose_name='URL'),
        ),
        migrations.AlterField(
            model_name='tweet',
            name='tweet_slug',
            field=models.CharField(default='article2024-10-22 14:48:09.923711', max_length=200, verbose_name='URL'),
        ),
        migrations.CreateModel(
            name='ClientCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('short_desc', models.TextField(blank=True, verbose_name='Описание')),
                ('sales', models.ManyToManyField(blank=True, to='recycle.clientsales')),
            ],
        ),
        migrations.AddField(
            model_name='client',
            name='client_category',
            field=models.ManyToManyField(blank=True, to='recycle.clientcategory'),
        ),
    ]
